In [2]:
import numpy as np

### 1-D Arrays

In [4]:
my_array = np.array([1,5,2])

### 2-D (and more Ds) Arrays

In [9]:
my_matrix = np.array([(1,2,3),(3,2,1),(6,4,5)])

my_tensor = np.array([[(1,2,3),(3,2,1),(6,4,5)],[(1,2,3),(3,2,1),(6,4,5)],[(1,2,3),(3,2,1),(6,4,5)]], dtype = float)

### What kind of array do you have?

In [11]:
print(my_array.shape, my_matrix.shape, my_tensor.shape)

(3,) (3, 3) (3, 3, 3)


### Array math

In [14]:
my_matrix

array([[1, 3, 6],
       [2, 2, 4],
       [3, 1, 5]])

In [15]:
my_matrix.T

array([[1, 2, 3],
       [3, 2, 1],
       [6, 4, 5]])

In [16]:
np.multiply(my_matrix, my_array)

array([[ 1, 10,  6],
       [ 3, 10,  2],
       [ 6, 20, 10]])

In [17]:
np.sin(my_array)

array([ 0.84147098, -0.95892427,  0.90929743])

In [18]:
my_array.dot(my_array)

30

### Getting from pandas dataframes to Numpy arrays

In [21]:
import pandas as pd

series = pd.Series([1, 2, 5])

numpy_array = series.to_numpy() 

print(type(numpy_array), numpy_array)

<class 'numpy.ndarray'> [1 2 5]
